### ISSUE TITLE
Re-work tests

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bech32#2]
They are currently using the address fixtures from https://github.com/sipa/bech32,  but with the address encoding/decoding eventually being removed...

They are failing as a result too.

**Comment by dcousens** [comment]
@afk11 I think the question I had here,  was can we isolate `bech32` encoding from the address encoding which I wanted to move to `bitcoinjs-lib`,  or similar.

The issue is the two concepts are [interleaved](https://github.com/bitcoinjs/bech32/blob/master/index.js#L39) here.

Probably not the biggest issue though... thoughts?

**Comment by kabutosamourai** [comment]
I think `convertBits` could easily be separated to remain in this Bech32-only library, with `bitcoinjs-lib` calling the helper function for encoding / decoding. SegWit address logic, coin prefixes, and script-version validation would move to `bitcoinjs-lib`. The small TODO over there would be converting witness programs to / from `scriptPubKey`s.

**Comment by afk11** [comment]
@dcousens Hmm, I think exposing encode/decode/convertBits here is OK. It is a bit weird that the high level bech32 encode accepts a 5-bit word list, though since specific address implementations can be done in bitcoinjs, people won't have to deal with bech32 much and if they do, they have everything they need here. 

Think @kabutosamourai's plan sounds about right. I'll take a look shortly if he hasn't started this already!

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bech32/pull/9
